import type { Metadata } from 'next'
import { Roboto as Inter } from 'next/font/google'
import { GeistSans } from 'geist/font/sans'
import './globals.css'
import Navbar from './components/Navbar'

const inter = Inter({
  subsets: ['latin'],
  weight: ['100', '300', '400', '700']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
